### ISSUE TITLE
Mac os x safari browser issue

### ISSUE THREAD

**Issue by SouhaibBenFarhat** [michaelsoriano/bootstrap-photo-gallery#17] opened 2018-01-10 01:43 UTC
Hello,

Awesome library, by running your demo on safari mac os browser, the preview image modal is not working
<img width="842" alt="screen shot 2018-01-10 at 2 42 44 am" src="https://user-images.githubusercontent.com/22856303/34751990-f625c31e-f5af-11e7-8b2c-57db114d95cd.png">

**Comment by michaelsoriano** [comment] 2018-01-10 17:31
ok will look asap.

**Comment by macsupport** [comment] 2018-01-28 16:47
The issue is that the modal's img src is set as: 
`<img src="url(path/to/your.jpg)" class="img-responsive bsp-modal-main-image">`
instead of:
`<img src="path/to/your.jpg" class="img-responsive bsp-modal-main-image">`

**Comment by AloysiusLeeson** [comment] 2018-01-30 09:49
macsupport is correct. I found a way to fix this - the problem appears to be the function 'getSrcfromStyle' at line 52 of jquery.bsPhotoGallery.js which reads:

`function getSrcfromStyle(istr){
        return istr.replace(/url\(\"/g,'').replace(/\"\)/g,'');    
      }`

Replace that with:
`function getSrcfromStyle(istr){
	      var temp1 = istr.substring(3);
	      var temp2 = temp1.substring(1,temp1.length-1);
        return temp2;    
      }
`
I hope this works for all cases - it worked for me.

**Comment by michaelsoriano** [comment] 2018-01-30 22:44
this is now fixed.

**Closed as completed by michaelsoriano** 2018-01-30 22:44 UTC
